# http://about.travis-ci.org/docs/user/build-configuration/
language: ruby

bundler_args: --without production development

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - "export JASMINE_BROWSER=firefox"
  - "firefox --version"

before_script:
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"

env:
  - DATABASE=mysql2

rvm:
  - 1.9.3
  - 2.0.0
